name: Fetch time series

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  update_readme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js version to ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Fetch cases data
        run: npm install && node scripts/update-data.js
        env:
          PROFILE_TOKEN: ${{ secrets.PROFILE_TOKEN }}
